export const Data2 = [
    {
        id : 62,
        Title : "OQQ Women's Yoga Rompers ",
        Cat : "WomenWears",
        brand  : "tshirts",
        isNew : true,
        description : "OQQ Women's Yoga Rompers Seamless Workout One Piece Padded Sports Bra Exercise Rompers",
        oldPrice : "16",
        Price : "13",
        Img : "/img/women/t-shirts/tshirts.png",
        bol : "/img/women/t-shirts/tshirtsi.png",
        sun : "/img/women/t-shirts/tshirtsii.jpg",
        images :'/img/women/hats/hats3.png'
          

    },
    {
        id:63,
        Title:"Laptop Bag for Women",
        Cat : "WomenWears",
        brand : 'bags',
        isNew : true,
        description : "Missnine Laptop Tote Bag Canvas Laptop Bag 15.6 inch Work Shoulder Bags Casual Briefcase Handbag for Travel, Office, College ",
        oldPrice : "23",
        Price: '21',
        Img : "/img/women/bags/bags1.png",
        bol : "/img/women/bags/bags1i.jpg",
        sun : "/img/women/bags/bags1ii.jpg",
    },
    {
        id:64,
        Title:"Parigi Stretch Pump",
        Cat : "WomenWears",
        brand : 'shoes',
        isNew : true,
        description : " LifeStride Women's Parigi Stretch Pump ",
        oldPrice : "30",
        Price: '24',
        Img : "/img/women/shoes/shoes1.png",
        bol : "/img/women/shoes/shoes1i.png",
        sun : "/img/women/shoes/shoes1ii.png",
    },
    {
        id:65,
        Title:"Original Stainless Steel Milanese Loop Compatible with Apple Watch",
        Cat : "WomenWears",
        brand : 'watches',
        isNew : true,
        description : " PAPERP Watch Band Compatible with Apple Watch Band Series Ultra 8 7 6 5 4 SE 38mm 40mm 41mm 42mm 44mm 45mm 49mm Women and Men Stainless Steel band,Milanese Loop Magnetic Clasp Replacement for iWatch bands (Starlight) ",
        oldPrice : "150",
        Price: '120',
        Img : "/img/women/watches/watches1.png",
        bol : "/img/women/watches/watches1i.png",
        sun : "/img/women/watches/watches1ii.png",
    },
    {
      id:66,
      Title:"Greenwald Crossbody Bag ",
      Cat : "WomenWears",
      brand : 'bags',
      isNew : true,
      description : " ALDO Women's Greenwald Crossbody Bag " ,     
      oldPrice : "47",
      Price: '44',
      Img : "/img/women/bags/bags3.png",
      bol : "/img/women/bags/bags3i.png",
      sun : "/img/women/bags/bags3ii.png",
    },
{
      id : 67,
      Title : "Calvin Klein",
      Cat : "WomenWears",
      brand  : "bags",
      isNew : true,
      description : " Calvin Klein Women's Gabrianna Novelty Bucket Shoulder Bag " ,     
      oldPrice : "56",
      Price : "52",
      Img : "/img/women/bags/bags2.png",
      bol : "/img/women/bags/bags2i.png",
      sun : "/img/women/bags/bags2ii.png",
    },
    {
      id:68,
      Title:"VONMELLI 2 Pack Women's Leather Belts ",
      Cat : "WomenWears",
      brand : 'belts',
      isNew : true,
      description : " VONMELLI 2 Pack Women's Leather Belts for Jeans Dresses Fashion Gold Buckle Ladies Belt " ,     
      oldPrice : "16",
      Price: '14',
      Img: '/img/women/belts/belts1.png',
      bol: '/img/women/belts/belts1i.png',
      sun: '/img/women/belts/belts1ii.jpg',
    },
    {
      id:69,
      Title:"JASGOOD Leather Skinny Women Belt",
      Cat : "WomenWears",
      brand : 'belts',
      isNew : true,
      description : " JASGOOD Leather Skinny Women Belt Thin Waist Belts for Dresses up to 37 Inches with Golden Buckle 2 Pack " ,     
      oldPrice : "30",
      Price: '29',
      Img: '/img/women/belts/belts3.png',
      bol: '/img/women/belts/belts3i.png',
      sun: '/img/women/belts/belts3ii.png',
    },
    {
      id:70,
      Title:"Womens Belts for Jeans",
      Cat : "WomenWears",
      brand : 'belts',
      isNew : true,
      description : "Womens Belts for Jeans, CR Womens Leather Belt with Gold Buckle, 1.15 Width Ladies Casual Belts for Jeans Pants " ,     
      oldPrice : 18,
      Price: '15',
      Img: '/img/women/belts/belts2.png',
      bol: '/img/women/belts/belts2i.png',
      sun: '/img/women/belts/belts2ii.png',
    },
    {
      id:71,
      Title:" Calvin Klein Women's Asymmetrical Wool Jacket ",
      Cat : "WomenWears",
      brand : 'coats',
      isNew : true,
      description : " Calvin Klein Women's Asymmetrical Wool Jacket " ,     
      oldPrice : "147",
      Price: '137',
      Img: '/img/women/coats/coats1.png',
      bol: '/img/women/coats/coats1i.png',
      sun: '/img/women/coats/coats1ii.png',
    },
{
      id : 72,
      Title : "Bankeng Women Winter Wool ",
      Cat : "WomenWears",
      brand  : "coats",
      isNew : true,
      description : " Bankeng Women Winter Wool Blend Camel Mid-Long Coat Notch Double-Breasted Lapel Jacket Outwear " ,     
      oldPrice : "56",
      Price : "49",
      Img: '/img/women/coats/coats3ii.png',
      bol: '/img/women/coats/coats3.png',
      sun: '/img/women/coats/coats3i.png',
    },
    {
      id:73,
      Title:"CAMELSPORTS Women's Waterproof Mountain Ski Snow Jacket",
      Cat : "WomenWears",
      brand : 'coats',
      isNew : true,
      description : " CAMELSPORTS Women's Waterproof Mountain Ski Snow Jacket with Fleece Outdoor Windproof Raincoat Hooded for Fall and Winter " ,     
      oldPrice : "58",
      Price: '55',
      Img: '/img/women/coats/coats2.png',
      bol: '/img/women/coats/coats2i.png',
      sun: '/img/women/coats/coats2ii.jpg',
    },
    {
      id:74,
      Title:"adidas Hat",
      Cat : "WomenWears",
      brand : 'hats',
      isNew : true,
      description : " adidas Women's Saturday Relaxed Fit Adjustable Hat " ,     
      oldPrice : "15",
      Price: '12',
      Img: '/img/women/hats/hats2.png',
      bol: '/img/women/hats/hats2i.png',
      sun: '/img/women/hats/hats2ii.png',
    },
    {
      id:75,
      Title:"Verabella Sun Hats",
      Cat : "WomenWears",
      brand : 'hats',
      isNew : true,
      description : " Verabella Sun Hats for Women UPF 50+ Women's Lightweight Foldable/Packable Beach Sun Hat " ,     
      oldPrice : "35",
      Price: '30',
      Img: '/img/women/hats/hats3.png',
      bol: '/img/women/hats/hats3i.png',
      sun: '/img/women/hats/hats3ii.png',
      
    },
    {
      id:76,
      Title:"VIEWLAP Cotton 100% Wide Brim Bucket Hat",
      Cat : "WomenWears",
      brand : 'hats',
      isNew : true,
      description : " VIEWLAP Cotton 100% Wide Brim Bucket Hat with Ribbon Point Mesh Lining Adjustable Sun Hat for Women Girls " ,     
      oldPrice : "47",
      Price: '37',
      Img: '/img/women/hats/hats1.png',
      bol: '/img/women/hats/hats1i.png',
      sun: '/img/women/hats/hats1ii.png',
    },
{
      id : 77,
      Title : "EFAN Womens Oversized Hoodies",
      Cat : "WomenWears",
      brand  : "hoodies",
      isNew : true,
      description : " EFAN Womens Oversized Hoodies Sweatshirts Fleece Hooded Pullover Tops Sweaters Casual Comfy Fall Fashion Outfits Clothes 2023 " ,     
      oldPrice : "28",
      Price : "25",
      Img: '/img/women/hoodies/hoodies3.png',
      bol: '/img/women/hoodies/hoodies3i.png',
      sun: '/img/women/hoodies/hoodies3ii.png',
    },
    {
      id:78,
      Title:"EFAN Womens Oversized Sweatshirts Pullover Hoodies ",
      Cat : "WomenWears",
      brand : 'hoodies',
      isNew : true,
      description : " EFAN Womens Oversized Sweatshirts Pullover Hoodies Fleece Sweaters Long Sleeve With Pockets Winter Fall Outfits Y2k Clothes " ,     
      oldPrice : "38",
      Price: '35',
      Img: '/img/women/hoodies/hoodies2.png',
      bol: '/img/women/hoodies/hoodies2i.png',
      sun: '/img/women/hoodies/hoodies2ii.png',
    },
    {
      id:79,
      Title:"Sleeve Pullover Hoodie",
      Cat : "WomenWears",
      brand : 'hoodies',
      isNew : true,
      description : " SweatyRocks Women's Casual Heart Print Long Sleeve Pullover Hoodie Sweatshirt Tops " ,     
      oldPrice : "19",
      Price: '16',
      Img: '/img/women/hoodies/hoodies1.png',
      bol: '/img/women/hoodies/hoodies1i.png',
      sun: '/img/women/hoodies/hoodies1ii.png',
    },
    {
      id:80,
      Title:"OQQ Women's 2 Piece Long Sleeve",
      Cat : "WomenWears",
      brand : 'tshirts',
      isNew : true,
      description : " OQQ Women's 2 Piece Long Sleeve Crew Neck Ruched Stretch Fitted Underscrubs Layer Tee Shirts Tops " ,     
      oldPrice : "30",
      Price: '25',
      Img : "/img/women/t-shirts/tshirts3.png",
      bol : "/img/women/t-shirts/tshirts3i.png",
      sun : "/img/women/t-shirts/tshirts3ii.png",
    },
    {
      id:81,
      Title:"MANGOPOP Women's V Neck",
      Cat : "WomenWears",
      brand : 'tshirts',
      isNew : true,
      description : " MANGOPOP Women's V Neck Short Sleeve Long Sleeve Slim Fit T Shirt Tunic Tops Tee " ,     
      oldPrice : "20",
      Price: '18',
      Img : "/img/women/t-shirts/tshirts1.png",
      bol : "/img/women/t-shirts/tshirts1i.png",
      sun : "/img/women/t-shirts/tshirts1ii.png",
    },
{
      id : 82,
      Title : "Hanes Women's Originals Cotton T-Shirt",
      Cat : "WomenWears",
      brand  : "tshirts",
      isNew : true,
      description : " Hanes Women's Originals Cotton T-Shirt, Classic Crewneck Women's Tee, Plus Size Available " ,     
      oldPrice : "16",
      Price : "14",
      Img : "/img/women/t-shirts/tshirts2.png",
      bol : "/img/women/t-shirts/tshirts2i.png",
      sun : "/img/women/t-shirts/tshirts2ii.png",
    },
    {
      id:83,
      Title:"The Drop Women's Paulina",
      Cat : "WomenWears",
      brand : 'shoes',
      isNew : true,
      description : " The Drop Women's Paulina Pointed Toe Two-Tone Mule " ,     
      oldPrice : "58",
      Price: '55',
      Img : "/img/women/shoes/shoes3.png",
      bol : "/img/women/shoes/shoes3i.png",
      sun : "/img/women/shoes/shoes3ii.png",
    },
    {
      id:84,
      Title:"REDTOP Women's Elastic Chelsea Boots",
      Cat : "WomenWears",
      brand : 'shoes',
      isNew : true,
      description : " REDTOP Women's Elastic Chelsea Boots Chunky Block Heel Platform Lug Sole Ankle Booties " ,     
      oldPrice : "44",
      Price: '36',
      Img : "/img/women/shoes/shoes2.png",
      bol : "/img/women/shoes/shoes2i.png",
      sun : "/img/women/shoes/shoes2ii.png",
    },
    {
      id:85,
      Title:" PUMA Women's Carina Sneaker ",
      Cat : "WomenWears",
      brand : 'shoes',
      isNew : true,
      description : " PUMA Women's Carina Sneaker " ,     
      oldPrice : "75",
      Price: '60',
      Img : "/img/women/shoes/shoes4.png",
      bol : "/img/women/shoes/shoes4i.png",
      sun : "/img/women/shoes/shoes4ii.png",
    },
    {
      id:86,
      Title:"Bnycuml Women's Casual Straight Trousers",
      Cat : "WomenWears",
      brand : 'trousers',
      isNew : true,
      description : " Bnycuml Women's Casual Straight Trousers High Waisted Button Work Office Dress Pants with Pockets " ,     
      oldPrice : "47",
      Price: '37',
      Img : "/img/women/trousers/trousers1.png",
      bol : "/img/women/trousers/trousers1i.png",
      sun : "/img/women/trousers/trousers1ii.png",
    },
{
      id : 87,
      Title : "SweatyRocks ",
      Cat : "WomenWears",
      brand  : "trousers",
      isNew : true,
      description : " SweatyRocks Women's Elegant High Waist Solid Long Pants Office Trousers " ,     
      oldPrice : "36",
      Price : "29",
      Img : "/img/women/trousers/trousers2.png",
      bol : "/img/women/trousers/trousers2i.png",
      sun : "/img/women/trousers/trousers2ii.png",
    },
    {
      id:88,
      Title:" Amazon Essentials Women's Skinny Jean ",
      Cat : "WomenWears",
      brand : 'trousers',
      isNew : true,
      description : " Amazon Essentials Women's Skinny Jean " ,     
      oldPrice : "38",
      Price: '35',
      Img : "/img/women/trousers/trousers3.png",
      bol : "/img/women/trousers/trousers3i.png",
      sun : "/img/women/trousers/trousers3ii.png",
    },
    {
      id:89,
      Title:"PLNOTME Women's High Waisted Jeans ",
      Cat : "WomenWears",
      brand : 'jeans',
      isNew : true,
      description : " PLNOTME Women's High Waisted Jeans Boyfriend Baggy Straight Leg Casual Denim Pants " ,     
      oldPrice : "40",
      Price: '34',
      Img : "/img/women/jeans/jeans2.png",
      bol : "/img/women/jeans/jeans2i.png",
      sun : "/img/women/jeans/jeans2ii.png",
    },
    {
      id:90,
      Title:"Boyfriend Jean ",
      Cat : "WomenWears",
      brand : 'jeans',
      isNew : true,
      description : " Lee Women's Mid Rise Boyfriend Jean " ,     
      oldPrice : "25",
      Price: '20',
      Img : "/img/women/trousers/trousers3.png",
      bol : "/img/women/trousers/trousers3i.png",
      sun : "/img/women/trousers/trousers3ii.png",
    },
    {
      id:91,
      Title:"PLNOTME Women's Fall Fashion",
      Cat : "WomenWears",
      brand : 'jeans',
      isNew : true,
      description : " PLNOTME Women's Fall Fashion 2023 High Waisted Baggy Jeans Straight Leg Button Fly Broken Waistband Denim Pants " ,     
      oldPrice : "47",
      Price: '37',
      Img : "/img/women/trousers/trousers1.png",
      bol : "/img/women/trousers/trousers1i.png",
      sun : "/img/women/trousers/trousers1ii.png",
    },
    {
      id:92,
      Title:"Long-Sleeve Button-Down Poplin Shirt ",
      Cat : "WomenWears",
      brand : 'shirts',
      isNew : true,
      description : " Amazon Essentials Women's Classic-Fit Long-Sleeve Button-Down Poplin Shirt " ,     
      oldPrice : "34",
      Price: '30',
      Img : "/img/women/shirts/shirts1.png",
      bol : "/img/women/shirts/shirts1i.png",
      sun : "/img/women/shirts/shirts1ii.png",
    },
    {
      id:93,
      Title:"Shirt Long Sleeve Collar Button Down Blouses Tops",
      Cat : "WomenWears",
      brand : 'shirts',
      isNew : true,
      description : " Lacozy Womens Buffalo Plaid Flannel Shirt Long Sleeve Collar Button Down Blouses Tops " ,     
      oldPrice : "27",
      Price: '25',
      Img : "/img/women/shirts/shirts2.png",
      bol : "/img/women/shirts/shirts2i.png",
      sun : "/img/women/shirts/shirts2ii.png",
    },
    {
      id:94,
      Title:"Shirt Collared Long Sleeve Blouse Top ",
      Cat : "WomenWears",
      brand : 'shirts',
      isNew : true,
      description : " WDIRARA Women's Colorblock Button Up Shirt Collared Long Sleeve Blouse Top " ,     
      oldPrice : "28",
      Price: '24',
      Img : "/img/women/shirts/shirts3.png",
      bol : "/img/women/shirts/shirts3i.png",
      sun : "/img/women/shirts/shirts3ii.png",
    },
    {
      id:95,
      Title:"Minimalist Analog Watch ",
      Cat : "WomenWears",
      brand : 'watches',
      isNew : true,
      description : " MVMT Signature Square Women's Minimalist Analog Watch " ,     
      oldPrice : "147",
      Price: '137',
      Img : "/img/women/watches/watches2.png",
      bol : "/img/women/watches/watches2i.png",
      sun : "/img/women/watches/watches2ii.png",
    },
    {
      id:96,
      Title:"Lola Rose Dainty Women's Wrist Watch",
      Cat : "WomenWears",
      brand : 'watches',
      isNew : true,
      description : " Lola Rose Dainty Women's Wrist Watch: Green Malachite Dial, Wrapped by Stylish Gift Box, Elegant Present for Ladies and Loved Ones " ,     
      oldPrice : "173",
      Price: '169',
      Img : "/img/women/watches/watches3.png",
      bol : "/img/women/watches/watches3i.png",
      sun : "/img/women/watches/watches3ii.png",
    },
    {
      id:97,
      Title:"Leather Strap Watch ",
      Cat : "WomenWears",
      brand : 'watches',
      isNew : true,
      description : " Anne Klein Women's Leather Strap Watch " ,     
      oldPrice : "24",
      Price: '23',
      Img : "/img/women/watches/watches4.png",
      bol : "/img/women/watches/watches4i.png",
      sun : "/img/women/watches/watches4ii.png",
    },
    {
      id:98,
      Title:"Blue Ray Computer Game Glasses",
      Cat : "WomenWears",
      brand : 'glasses',
      isNew : true,
      description : " ANRRI Blue Light Blocking Glasses Round Eyeglasses Frame Filter Blue Ray Computer Game Glasses " ,     
      oldPrice : "21",
      Price: '20',
      Img : "/img/women/glassess/glassess2.png",
      bol : "/img/women/glassess/glassess2i.png",
      sun : "/img/women/glassess/glassess2ii.png",
    },
    {
      id:99,
      Title:"REAVEE 3 Pack Oprah Style Reading Glasses",
      Cat : "WomenWears",
      brand : 'glasses',
      isNew : true,
      description : " REAVEE 3 Pack Oprah Style Reading Glasses for Women,Blue Light Blocking Cute Oversized Square Computer Readers Spring Hinge " ,     
      oldPrice : "13",
      Price: '11',
      Img : "/img/women/glassess/glassess1.png",
      bol : "/img/women/glassess/glassess1i.png",
      sun : "/img/women/glassess/glassess1ii.png",
    },
    {
      id:100,
      Title:"FONHCOO Blue Light Blocking Glasses",
      Cat : "WomenWears",
      brand : 'glasses',
      isNew : true,
      description : " FONHCOO Blue Light Blocking Glasses Fashion Round TR90 Frame Transparent Eyewear Anti UV Computer Glasses for Women Men " ,     
      oldPrice : "18",
      Price: '15',
      Img : "/img/women/glassess/glassess3.png",
      bol : "/img/women/glassess/glassess3i.png",
      sun : "/img/women/glassess/glassess3ii.png",
    },
]