export const Womandetails = [
    {
        id : 1,
        Title : "OQQ Women's Yoga Rompers ",
        Cat : "women",
        isNew : true,
        oldPrice : "16",
        Price : "13",
        Img : "./img/women/harmless.png"
    },
    {
        id:2,
        Title:"Laptop Bag for Women",
        Cat: 'women',
        isNew : true,
        oldPrice : "23",
        Price: '21',
        Img: './img/women/71j2CutppQL._AC_SX679_.png',
    },
    {
        id:3,
        Title:"LifeStride Women's Parigi Stretch Pump",
        Cat: 'women',
        isNew : true,
        oldPrice : "30",
        Price: '24',
        Img: './img/women/71KjamXpFyL._AC_UX695_.png',
    },
    {
        id:4,
        Title:"Original Stainless Steel Milanese Loop Compatible with Apple Watch",
        Cat: 'women',
        isNew : true,
        oldPrice : "15",
        Price: '12',
        Img: './img/women/81EarhLNLGL._AC_SX679_.png',
    },
    {
        id:5,
        Title:"Blue Ray Computer Game Glasses",
        tags : "Women",
        Cat: 'women',
        isNew : true,
        description : " ANRRI Blue Light Blocking Glasses Round Eyeglasses Frame Filter Blue Ray Computer Game Glasses " ,     
        oldPrice : "21",
        Price: '20',
        Img : "/img/women/glassess/glassess2.png",
      },
    {
        id : 6,
        Title : "JMIERR Mens Flannel Shirts",
        Cat : "men",
        isNew : true,
        oldPrice : "34",
        Price : "32",
        Img : "./img/men/71aAVoHykoL._AC_UY879_.png"
    },
    {
        id:7,
        Title:"Berliner Bags Vintage Leather",
        Cat: 'men',
        isNew : true,
        oldPrice : "170",
        Price: '139',
        Img: './img/men/71po1OviJIL._AC_SX679_.png',
    },
    {
        id:8,
        Title:"Men’s Dress Oxford Formal Shoes",
        Cat: 'men',
        isNew : true,
        oldPrice : "84",
        Price: '85',
        Img: './img/men/81EAgRdZFpL._AC_UY695_.png',
    },
    {
        id:9,
        Title:"Baililai Unisex Polarized Sunglasses",
        Cat: 'men',
        isNew : true,
        oldPrice : "30",
        Price: '21',
        Img: './img/men/41BCpNjEPKL._AC_UX679_.png',
    },
    {
        id:10,
        Title:"Baililai Unisex Polarized Sunglasses",
        Cat: 'men',
        isNew : true,
        oldPrice : "30",
        Price: '21',
        Img: './img/men/41BCpNjEPKL._AC_UX679_.png',
    },
    {
        id : 11,
        Title : "XUANHAO Baby Boy Clothes",
        Cat : "children",
        isNew : true,
        oldPrice : "23",
        Price : "21",
        Img : "./img/children/81w6HNUqo4L._AC_UX679_.png"
    },
    {
        id:12,
        Title:"HawLander Preschool Kids Backpack",
        Cat: 'children',
        isNew : true,
        oldPrice : "30",
        Price: '24',
        Img: './img/children/81mekQX1UUL._AC_UX679_.png',
    },
    {
        id:13,
        Title:"GINFIVE Toddler Girls",
        Cat: 'children',
        isNew : true,
        oldPrice : "26",
        Price: '19',
        Img: './img/children/71n4mt-1ByL._AC_UY695_.png',
    },
    {
        id:14,
        Title:"Child Seat Belt Adjusters",
        Cat: 'children',
        isNew : true,
        oldPrice : "12",
        Price: '11',
        Img: './img/children/613q8Gde++L._SX679_.png',
    },
    {
        id:15,
        Title:"Child Seat Belt Adjusters",
        Cat: 'children',
        isNew : true,
        oldPrice : "12",
        Price: '11',
        Img: './img/children/613q8Gde++L._SX679_.png',
    },
    {
        id : 16,
        Cat : "beauty",
        Title : "IMAGE Skincare",
        isNew : true,
        oldPrice : "40",
        Price : "30",
        Img : "./img/beauty/beauty1.png"
    },
    {
        id:17,
        Title:"Gillette Venus Intimate Grooming Womens Electric Razor",
        Cat: 'beauty',
        isNew : true,
        oldPrice : "30",
        Price: '29',
        Img: './img/beauty/beauty2.png',
    },
    {
        id:18,
        Title:"Finishing Touch Flawless Bikini Shaver",
        Cat: 'beauty',
        isNew : true,
        oldPrice : "10",
        Price: '9',
        Img: './img/beauty/beauty3.png',
    },
    {
        id:19,
        Title:"Cayzor Bikini Trimmer and Shaver",
        Cat: 'beauty',
        isNew : true,
        oldPrice : "26",
        Price: '23',
        Img: './img/beauty/beauty4.png',
    },
    {
        id:20,
        Title:"Cayzor Bikini Trimmer and Shaver",
        Cat: 'beauty',
        isNew : true,
        oldPrice : "26",
        Price: '23',
        Img: './img/beauty/beauty4.png',
    },
    {
        id : 21,
        Title : "The Shadow Work Journal",
        Cat : "books",
        isNew : true,
        oldPrice : "30",
        Price : "25",
        Img : "./img/books/books1.jpg"
    },
    {
        id:22,
        Title:"The Democrat Party Hates America",
        Cat: 'books',
        isNew : true,
        oldPrice : "17",
        Price: '14',
        Img: './img/books/61sp+sMfrXL._SL1500_.jpg',
    },
    {
        id:23,
        Title:"Iron Flame",
        Cat: 'books',
        isNew : true,
        oldPrice : "18",
        Price: '14',
        Img: './img/books/91ke43dIxkL._SL1500_.jpg',
    },
    {
        id:24,
        Title:"Build the Life You Want",
        Cat: 'books',
        isNew : true,
        oldPrice : "18",
        Price: '15',
        Img: './img/books/81+MJor-K6L._SL1500_.jpg',
    },
    {
        id:25,
        Title:"Build the Life You Want",
        Cat: 'books',
        isNew : true,
        oldPrice : "18",
        Price: '15',
        Img: './img/books/81+MJor-K6L._SL1500_.jpg',
    },
    {
        id : 26,
        Cat : "computer",
        Title : "HP 2022 Stream 14 HD BrightView Laptop",
        isNew : true,
        oldPrice : "309",
        Price : "300",
        Img : "./img/computer/laptop1.png"
    },
    {
        id:27,
        Title:"2023 Newest Upgraded IdeaPad 1i Laptops",
        Cat: 'computer',
        isNew : true,
        oldPrice : "400",
        Price: '390',
        Img: './img/computer/laptop2.png',
    },
    {
        id:28,
        Title:"Dell OptiPlex Computer Desktop PC",
        Cat: 'computer',
        isNew : true,
        oldPrice : "259",
        Price: '203',
        Img: './img/computer/laptop3.png',
    },
    {
        id:29,
        Title:"HP 14 Laptop",
        Cat: 'computer',
        isNew : true,
        oldPrice : "200",
        Price: '196',
        Img: './img/computer/laptop4.png',
    },
    {
        id:30,
        Title:"HP 14 Laptop",
        Cat: 'computer',
        isNew : true,
        oldPrice : "200",
        Price: '196',
        Img: './img/computer/laptop4.png',
    },
    {
        id : 31,
        Title : "iPhone Fast Charger",
        Cat : "electronics",
        isNew : true,
        oldPrice : "16",
        Price : "12",
        Img : "./img/electronics/electronics1.png"
    },
    {
        id:32,
        Title:"Duracell Optimum AAA Batteries",
        Cat: 'electronics',
        isNew : true,
        oldPrice : "14",
        Price: '10',
        Img: './img/electronics/electronics2.png',
    },
    {
        id:33,
        Title:"Intoval 3-in-1 Wireless Charging Station",
        Cat: 'electronics',
        isNew : true,
        oldPrice : "49",
        Price: '34',
        Img: './img/electronics/electronics3.png',
    },
    {
        id:34,
        Title:"Compressed Air Duster & Mini Vacuum Keyboard Cleaner",
        Cat: 'electronics',
        isNew : true,
        oldPrice : "35",
        Price: '29',
        Img: './img/electronics/electronics4.png',
    },
    {
        id:35,
        Title:"Compressed Air Duster & Mini Vacuum Keyboard Cleaner",
        Cat: 'electronics',
        isNew : true,
        oldPrice : "35",
        Price: '29',
        Img: './img/electronics/electronics4.png',
    },
    {
        id : 36,
        Cat : "food",
        Title : "Breville Sous Chef",
        isNew : true,
        oldPrice : "723",
        Price : "549",
        Img : "./img/food/food1.png"
    },
    {
        id:37,
        Title:"Kellogg's Cold Breakfast Cereal",
        Cat: 'food',
        isNew : true,
        oldPrice : "28",
        Price: '27',
        Img: './img/food/food2.png',
    },
    {
        id:38,
        Title:"Hazel & Creme Cookies Gift Basket ",
        Cat: 'food',
        isNew : true,
        oldPrice : "23",
        Price: '21',
        Img: './img/food/food3.png',
    },
    {
        id:39,
        Title:"VEVOR 6-Pan Commercial Food Warmer",
        Cat: 'food',
        isNew : true,
        oldPrice : "525",
        Price: '400',
        Img: './img/food/food4.png',
    },
    {
        id:40,
        Title:"VEVOR 6-Pan Commercial Food Warmer",
        Cat: 'food',
        isNew : true,
        oldPrice : "525",
        Price: '400',
        Img: './img/food/food4.png',
    },
    {
        id : 41,
        Cat : "health",
        Title : "Schneider Nitrile Exam Gloves",
        isNew : true,
        oldPrice : "10",
        Price : "7",
        Img : "./img/health/health1.png"
    },
    {
        id:42,
        Title:"Mop Replace Head",
        Cat: 'health',
        isNew : true,
        oldPrice : "15",
        Price: '11',
        Img: './img/health/health2.png',
    },
    {
        id:43,
        Title:"JOYMOOP Mop and Bucket",
        Cat: 'health',
        isNew : true,
        oldPrice : "59",
        Price: '42',
        Img: './img/health/health3.png',
    },
    {
        id:44,
        Title:"KEEPOW Reusable Microfiber Mop Pads",
        Cat: 'health',
        isNew : true,
        oldPrice : "17",
        Price: '16',
        Img: './img/health/health4.png',
    },
    {
        id:45,
        Title:"KEEPOW Reusable Microfiber Mop Pads",
        Cat: 'health',
        isNew : true,
        oldPrice : "17",
        Price: '16',
        Img: './img/health/health4.png',
    },
    {
        id : 46,
        Title : "KitchenAid ",
        Cat : "home",
        isNew : true,
        oldPrice : "12",
        Price : "11",
        Img : "./img/home/home1.png"
    },
    {
        id:47,
        Title:"Stand Mixer",
        Cat: 'home',
        isNew : true,
        oldPrice : "300",
        Price: '199',
        Img: './img/home/home2.png',
    },
    {
        id:48,
        Title:"Dish Drying Rack",
        Cat: 'home',
        isNew : true,
        oldPrice : "35",
        Price: '29',
        Img: './img/home/home3.png',
    },
    {
        id:49,
        Title:"Cisily Sponge Holder",
        Cat: 'home',
        isNew : true,
        oldPrice : "20",
        Price: '15',
        Img: './img/home/home4.png',
    },
    {
        id:50,
        Title:"Cisily Sponge Holder",
        Cat: 'home',
        isNew : true,
        oldPrice : "20",
        Price: '15',
        Img: './img/home/home4.png',
    },
    {
        id : 51,
        Cat : "luggage",
        Title : "Fanskey Luggage, 3 Piece Set Suitcase",
        isNew : true,
        oldPrice : "250",
        Price : "210",
        Img : "./img/luggage/luggage1.png"
    },
    {
        id:52,
        Title:"Coolife Suitcase Set 3 Piece Luggage",
        Cat: 'luggage',
        isNew : true,
        oldPrice : "299",
        Price: '109',
        Img: './img/luggage/luggage2.png',
    },
    {
        id:53,
        Title:"Hanke 20 Inch Carry On Luggage",
        Cat: 'luggage',
        isNew : true,
        oldPrice : "267",
        Price: '169',
        Img: './img/luggage/luggage3.png',
    },
    {
        id:54,
        Title:"Rockland Fashion Softside Upright Luggage",
        Cat: 'luggage',
        isNew : true,
        oldPrice : "60",
        Price: '45',
        Img: './img/luggage/luggage4.png',
    },
    {
        id:55,
        Title:"Rockland Fashion Softside Upright Luggage",
        Cat: 'luggage',
        isNew : true,
        oldPrice : "60",
        Price: '45',
        Img: './img/luggage/luggage4.png',
    },
    {
        id : 56,
        Cat : "phones",
        Title : "Motorola Moto G Stylus",
        isNew : true,
        oldPrice : "159",
        Price : "149",
        Img : "./img/phones/phones1.png"
    },
    {
        id:57,
        Title:"SAMSUNG Galaxy A34",
        Cat: 'phones',
        isNew : true,
        oldPrice : "299",
        Price: '248',
        Img: './img/phones/phones2.png',
    },
    {
        id:58,
        Cat: 'phones',
        Title:"iPhone 13 Pro",
        isNew : true,
        oldPrice : "1000",
        Price: '948',
        Img: './img/phones/phones3.png',
    },
    {
        id:59,
        Title:"SAMSUNG Galaxy Z Flip",
        Cat: 'phones',
        isNew : true,
        oldPrice : "1000",
        Price: '940',
        Img: './img/phones/phones4.png',
    },
    {
        id:60,
        Title:"SAMSUNG Galaxy Z Flip",
        Cat: 'phones',
        isNew : true,
        oldPrice : "1000",
        Price: '940',
        Img: './img/phones/phones4.png',
    },
]
